CREATE TABLE `user` (
   `ID` int(11) NOT NULL,
   `UID` varchar(64) DEFAULT NULL,
   `EMAIL` varchar(64) DEFAULT NULL,
   `PHONE` varchar(32) DEFAULT NULL,
   `ROLE` varchar(16) DEFAULT NULL,
   `NICK_NAME` varchar(32) DEFAULT NULL,
   `STATUS` tinyint(4) DEFAULT NULL,
   `PWD` varchar(32) DEFAULT NULL,
   `ADD_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   `SALT` varchar(32) DEFAULT NULL,
   PRIMARY KEY (`ID`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4